import * as fs from 'fs';
import * as path from 'path';
import * as glob from 'glob';

const rootDir = path.resolve(__dirname, '..');
const rootPackageJsonPath = path.join(rootDir, 'package.json');

// Read root package.json
const rootPackageJson = JSON.parse(fs.readFileSync(rootPackageJsonPath, 'utf8'));
const newVersion = rootPackageJson.version;

console.log(`Syncing version ${newVersion} to all packages...`);

// Find all package.json files in workspaces
// Assuming standard pnpm workspace layout: apps/* and packages/*
const workspacePatterns = ['apps/*/package.json', 'packages/*/package.json'];

workspacePatterns.forEach((pattern) => {
  const files = glob.sync(pattern, { cwd: rootDir, absolute: true });

  files.forEach((filePath: string) => {
    const packageJson = JSON.parse(fs.readFileSync(filePath, 'utf8'));

    if (packageJson.version !== newVersion) {
      console.log(`Updating ${packageJson.name} from ${packageJson.version} to ${newVersion}`);
      packageJson.version = newVersion;
      fs.writeFileSync(filePath, JSON.stringify(packageJson, null, 2) + '\n');
    } else {
      console.log(`Skipping ${packageJson.name} (already at ${newVersion})`);
    }
  });
});

// Update tauri.conf.json version
const tauriConfPath = path.join(rootDir, 'apps/frontend/src-tauri/tauri.conf.json');
const tauriConf = JSON.parse(fs.readFileSync(tauriConfPath, 'utf8'));

if (tauriConf.version !== newVersion) {
  console.log(`Updating tauri.conf.json from ${tauriConf.version} to ${newVersion}`);
  tauriConf.version = newVersion;
  fs.writeFileSync(tauriConfPath, JSON.stringify(tauriConf, null, 2) + '\n');
} else {
  console.log(`Skipping tauri.conf.json (already at ${newVersion})`);
}

// Generate version.ts in frontend src/lib
const frontendVersionPath = path.join(rootDir, 'apps/frontend/src/lib/version.ts');
const versionFileContent = `// Auto-generated by sync-version script - DO NOT EDIT
export const APP_VERSION = '${newVersion}';
`;

fs.writeFileSync(frontendVersionPath, versionFileContent);
console.log(`Updated ${frontendVersionPath}`);

console.log('Version sync complete.');
